### ISSUE TITLE
Nothing happens when I type pc.command

### ISSUE THREAD

**Issue by atx840** [PizzaConsole/DiscordCopyBot#1]
I added the bot to both servers, admin privileges and when pc.copychannel is entered nothing happens.  If I message the bot with it I do get the response "Which Channel would you like to copy? (copy and paste the Id) Pleaes wait while I find all of your channels, I will give you a message when I have found them all."

**Comment by PizzaConsole** [comment]
I have updated the readme, let me know if it makes sense.

**Comment by atx840** [comment]
Thank you, that def helps to know the other commands.

When I type pc.copychannel, still nothing happens.  Apologies if I am missing something.

**Comment by PizzaConsole** [comment]
and you are typing it in a discord server where the bot has admin permissions and you can see the bot online in the right hand side when you are in the channel?

![image](https://user-images.githubusercontent.com/60050783/107399550-12ff8c00-6abe-11eb-9f7e-57cb849621c5.png)

**Comment by PizzaConsole** [comment]
updated the readme again NOTE: You must be the OWNER (Not just an admin) of BOTH servers)

**Comment by atx840** [comment]
Ah that was it, thank you!  Now I can test.

Cheers,

**Comment by PizzaConsole** [comment]
Yup, thanks for using it! I am glad I can help!

**Comment by PizzaConsole** [comment]
I actually investigated this a bit more, you can use it as an admin, but for some reason, you have to run `pc.help` AFTER you are given the Admin role and then it will recognize you as authorized...

**Comment by PizzaConsole** [comment]
even then it appears to have issues, I will have to investigate, better to just stick with having to be an owner

**Comment by atx840** [comment]
it works great as an owner.  I also just use the pc.loadchannel command and update the IDs, doesnt require the copy command every time
Thank your making this.

**Comment by PizzaConsole** [comment]
correct, the `pc.copychannel` command is just to list the IDs, once you have them you can just use the `pc.loadchannel`command.

**Comment by atx840** [comment]
This is great, wonder if there is a way to move a whole category with channels and messages.  Great bot sir.

**Comment by PizzaConsole** [comment]
Thanks! There is a lot of extra functionality that I can implement here, its just a matter of finding the time XD, I built this because I needed it and the only other one I could find was one that charged you $$$$ and only copied the previous 100 messages....

**Comment by atx840** [comment]
Hey!

Noticed the bot went offline.  We have been using it multiple times a day, it is very helpful.

Is there a way I can build my own with your code or host it somewhere?  

Cheers,

Chris

**Comment by PizzaConsole** [comment]
@atx840  I can try and put some documentation as to how you can do self hosting, it will take me a few days to get to it. Sorry about the bot going down, I was doing some server maintenance.

**Comment by atx840** [comment]
Totally appreciate it.  I know a bit about development (not discord) and am trying to research.  I have modified your config but I'm not sure its correct and what to do next.  Ill have to find a host, I have used digital ocean or heroku for some of my python apps.

Yeah we run a discord with now over 800 channels and we have to keep moving to keep each under the 500 limit.  The bot is crucial, could offer some funds for your time

C

**Comment by atx840** [comment]
Hey,

I havent been working on that project for a month+ but asked that the current lead reach out to you.  I doubt the ever did. Sorry about that.

Is there a way to bring the bot back, maybe a few more months of hosting costs or if you could just set one up for me I’d pay for your time like we discussed.  They are bugging me :)

Cheers,

C
